### ISSUE TITLE
Find motifs between different series

### ISSUE THREAD

**Issue by BeastyBlacksmith** [johncwok/MotifRecognition.jl#2]
How hard would it be to alter the package to have the option to look for Motifs in a collection of series?

**Comment by CNelias** [comment]
Would these series have the same statistical distribution, or do they originate from different processes?

**Comment by BeastyBlacksmith** [comment]
The former, I'm thinking of series that originate from the same process

**Comment by CNelias** [comment]
Then that shouldn't be too difficult, I think. I'll have a closer look at it this weekend and let you know.

**Comment by CNelias** [comment]
@BeastyBlacksmith Done. You can now also input your different measurements series as a vector of vector or as a matrix. I'll update the doc soon.
